namespace Flux.Core
{
    public static class Localizer
    {
        private static string _lang = "it";

        public static void SetLanguage(string lang) =>
            _lang = lang is "it" or "en" or "fr" ? lang : "it";

        public static string Get(string key) =>
            (_lang == "en" ? _en : _lang == "fr" ? _fr : _it)
                .TryGetValue(key, out var v) ? v : key;

        // ── ITALIANO ──────────────────────────────────────────────────────────
        private static readonly Dictionary<string, string> _it = new()
        {
            // MainWindow nav & titles
            ["nav_tweaks"]    = "  TWEAKS",
            ["nav_monitor"]   = "  MONITOR",
            ["nav_premium"]   = "  PREMIUM",
            ["nav_account"]   = "ACCOUNT",
            ["nav_overview"]  = "OVERVIEW",
            ["title_tweaks"]  = "T W E A K S",
            ["sub_tweaks"]    = "   Ottimizzazione sistema",
            ["title_monitor"] = "M O N I T O R",
            ["sub_monitor"]   = "   Hardware in tempo reale",
            ["label_free"]    = "F R E E",
            ["label_premium_header"] = "* PREMIUM",
            ["label_unlock"]  = "* Sblocca  5 EUR",
            ["label_adv_tweaks"]  = "18 tweaks avanzati",
            ["label_adv_monitor"] = "7 monitor avanzati",
            ["label_live"]    = "L I V E",
            ["btn_apply"]     = "A P P L Y",
            ["btn_flush"]     = "F L U S H",
            ["btn_disable"]   = "D I S A B L E",
            ["btn_clean"]     = "C L E A N",
            ["btn_execute"]   = "E S E G U I",
            ["btn_unlocked"]  = "UNLOCKED",
            // Account
            ["plan_free"]     = "Free",
            ["plan_premium"]  = "Premium",
            ["plan_admin"]    = "Admin",
            // Settings
            ["settings_title"]    = "S E T T I N G S",
            ["settings_language"] = "L A N G U A G E",
            ["settings_theme"]    = "T H E M E",
            ["settings_about"]    = "A B O U T",
            ["settings_key"]      = "L I C E N Z A",
            ["settings_key_placeholder"] = "FLUX-XXXX-XXXX-XXXX-XXXX",
            ["settings_key_activate"]    = "A T T I V A",
            ["settings_key_ok"]          = "Premium attivo!",
            ["settings_key_used"]        = "Key gia utilizzata.",
            ["settings_key_invalid"]     = "Key non valida.",
            ["settings_version"]         = "Version 1.0.0 — 2026",
            ["settings_status_admin"]    = "Account Admin — tutti i tweak sbloccati",
            ["settings_status_premium"]  = "Account Premium — tutti i tweak sbloccati",
            ["settings_status_free"]     = "Account Free — 8 tweak attivi",
            // Login
            ["login_title"]    = "F L U X",
            ["login_sub"]      = "SYSTEM MONITOR",
            ["login_tab"]      = "LOGIN",
            ["register_tab"]   = "REGISTRATI",
            ["login_user"]     = "Username",
            ["login_pass"]     = "Password",
            ["login_btn"]      = "A C C E D I",
            ["login_remember"] = "Ricordami al prossimo avvio",
            ["reg_user"]       = "Username",
            ["reg_pass"]       = "Password",
            ["reg_confirm"]    = "Conferma password",
            ["reg_btn"]        = "R E G I S T R A T I",
            // Premium window
            ["prem_title"]     = "F L U X  P R E M I U M",
            ["prem_unlock"]    = "  UNLOCK PREMIUM  ",
            ["prem_desc"]      = "Ottieni accesso a 18 Tweaks avanzati",
            ["prem_paypal"]    = "P A G A  C O N  P A Y P A L",
            ["prem_once"]      = "Una tantum — nessun abbonamento",
        };

        // ── ENGLISH ───────────────────────────────────────────────────────────
        private static readonly Dictionary<string, string> _en = new()
        {
            ["nav_tweaks"]    = "  TWEAKS",
            ["nav_monitor"]   = "  MONITOR",
            ["nav_premium"]   = "  PREMIUM",
            ["nav_account"]   = "ACCOUNT",
            ["nav_overview"]  = "OVERVIEW",
            ["title_tweaks"]  = "T W E A K S",
            ["sub_tweaks"]    = "   System optimization",
            ["title_monitor"] = "M O N I T O R",
            ["sub_monitor"]   = "   Hardware real time",
            ["label_free"]    = "F R E E",
            ["label_premium_header"] = "* PREMIUM",
            ["label_unlock"]  = "* Unlock  5 EUR",
            ["label_adv_tweaks"]  = "18 advanced tweaks",
            ["label_adv_monitor"] = "7 advanced monitors",
            ["label_live"]    = "L I V E",
            ["btn_apply"]     = "A P P L Y",
            ["btn_flush"]     = "F L U S H",
            ["btn_disable"]   = "D I S A B L E",
            ["btn_clean"]     = "C L E A N",
            ["btn_execute"]   = "E X E C U T E",
            ["btn_unlocked"]  = "UNLOCKED",
            ["plan_free"]     = "Free",
            ["plan_premium"]  = "Premium",
            ["plan_admin"]    = "Admin",
            ["settings_title"]    = "S E T T I N G S",
            ["settings_language"] = "L A N G U A G E",
            ["settings_theme"]    = "T H E M E",
            ["settings_about"]    = "A B O U T",
            ["settings_key"]      = "L I C E N S E",
            ["settings_key_placeholder"] = "FLUX-XXXX-XXXX-XXXX-XXXX",
            ["settings_key_activate"]    = "A C T I V A T E",
            ["settings_key_ok"]          = "Premium activated!",
            ["settings_key_used"]        = "Key already used.",
            ["settings_key_invalid"]     = "Invalid key.",
            ["settings_version"]         = "Version 1.0.0 — 2026",
            ["settings_status_admin"]    = "Admin Account — all tweaks unlocked",
            ["settings_status_premium"]  = "Premium Account — all tweaks unlocked",
            ["settings_status_free"]     = "Free Account — 8 active tweaks",
            ["login_title"]    = "F L U X",
            ["login_sub"]      = "SYSTEM MONITOR",
            ["login_tab"]      = "LOGIN",
            ["register_tab"]   = "REGISTER",
            ["login_user"]     = "Username",
            ["login_pass"]     = "Password",
            ["login_btn"]      = "L O G  I N",
            ["login_remember"] = "Remember me on next launch",
            ["reg_user"]       = "Username",
            ["reg_pass"]       = "Password",
            ["reg_confirm"]    = "Confirm password",
            ["reg_btn"]        = "R E G I S T E R",
            ["prem_title"]     = "F L U X  P R E M I U M",
            ["prem_unlock"]    = "  UNLOCK PREMIUM  ",
            ["prem_desc"]      = "Get access to 18 advanced Tweaks",
            ["prem_paypal"]    = "P A Y  W I T H  P A Y P A L",
            ["prem_once"]      = "One time — no subscription",
        };

        // ── FRANCAIS ──────────────────────────────────────────────────────────
        private static readonly Dictionary<string, string> _fr = new()
        {
            ["nav_tweaks"]    = "  TWEAKS",
            ["nav_monitor"]   = "  MONITEUR",
            ["nav_premium"]   = "  PREMIUM",
            ["nav_account"]   = "COMPTE",
            ["nav_overview"]  = "APERCU",
            ["title_tweaks"]  = "T W E A K S",
            ["sub_tweaks"]    = "   Optimisation du systeme",
            ["title_monitor"] = "M O N I T E U R",
            ["sub_monitor"]   = "   Materiel en temps reel",
            ["label_free"]    = "G R A T U I T",
            ["label_premium_header"] = "* PREMIUM",
            ["label_unlock"]  = "* Debloquer  5 EUR",
            ["label_adv_tweaks"]  = "18 tweaks avances",
            ["label_adv_monitor"] = "7 moniteurs avances",
            ["label_live"]    = "E N  D I R E C T",
            ["btn_apply"]     = "A P P L I Q U E R",
            ["btn_flush"]     = "V I D E R",
            ["btn_disable"]   = "D E S A C T I V E R",
            ["btn_clean"]     = "N E T T O Y E R",
            ["btn_execute"]   = "E X E C U T E R",
            ["btn_unlocked"]  = "DEBLOQUE",
            ["plan_free"]     = "Gratuit",
            ["plan_premium"]  = "Premium",
            ["plan_admin"]    = "Admin",
            ["settings_title"]    = "P A R A M E T R E S",
            ["settings_language"] = "L A N G U E",
            ["settings_theme"]    = "T H E M E",
            ["settings_about"]    = "A  P R O P O S",
            ["settings_key"]      = "L I C E N C E",
            ["settings_key_placeholder"] = "FLUX-XXXX-XXXX-XXXX-XXXX",
            ["settings_key_activate"]    = "A C T I V E R",
            ["settings_key_ok"]          = "Premium active!",
            ["settings_key_used"]        = "Cle deja utilisee.",
            ["settings_key_invalid"]     = "Cle invalide.",
            ["settings_version"]         = "Version 1.0.0 — 2026",
            ["settings_status_admin"]    = "Compte Admin — tous les tweaks debloques",
            ["settings_status_premium"]  = "Compte Premium — tous les tweaks debloques",
            ["settings_status_free"]     = "Compte Gratuit — 8 tweaks actifs",
            ["login_title"]    = "F L U X",
            ["login_sub"]      = "SYSTEM MONITOR",
            ["login_tab"]      = "CONNEXION",
            ["register_tab"]   = "INSCRIPTION",
            ["login_user"]     = "Nom d'utilisateur",
            ["login_pass"]     = "Mot de passe",
            ["login_btn"]      = "C O N N E X I O N",
            ["login_remember"] = "Se souvenir au prochain lancement",
            ["reg_user"]       = "Nom d'utilisateur",
            ["reg_pass"]       = "Mot de passe",
            ["reg_confirm"]    = "Confirmer le mot de passe",
            ["reg_btn"]        = "S ' I N S C R I R E",
            ["prem_title"]     = "F L U X  P R E M I U M",
            ["prem_unlock"]    = "  DEBLOQUER PREMIUM  ",
            ["prem_desc"]      = "Acceder a 18 Tweaks avances",
            ["prem_paypal"]    = "P A Y E R  A V E C  P A Y P A L",
            ["prem_once"]      = "Paiement unique — sans abonnement",
        };
    }
}